import React, { useState } from 'react';
import { Sparkles, Copy, Download, CheckCheck } from 'lucide-react';
import { showToast } from '../utils/toast';

/**
 * AISummary Component
 * Displays the patient-friendly AI-generated summary with copy and download actions.
 *
 * @param {string} summary - The patient-friendly summary text from Gemini
 * @param {string} reportTitle - Report title for download filename
 */
const AISummary = ({ summary, reportTitle = 'Medical Report' }) => {
  const [copied, setCopied] = useState(false);

  if (!summary) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      showToast.success('Summary copied to clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = summary;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      showToast.success('Summary copied!');
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handleDownload = () => {
    const content = `MediTrack AI Summary\n${'='.repeat(40)}\nReport: ${reportTitle}\nGenerated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n\n${summary}\n\n${'─'.repeat(40)}\nGenerated by MediTrack using Gemini AI.\nThis summary is for informational purposes only. Always consult a qualified healthcare professional for medical advice.`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportTitle.replace(/\s+/g, '_')}_AI_Summary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast.success('Summary downloaded!');
  };

  return (
    <div className="rounded-2xl overflow-hidden border border-blue-200 dark:border-[#2A2C30] bg-white dark:bg-[#17181A] shadow-sm transition-colors">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-violet-600 dark:from-[#17181A] dark:to-[#17181A] dark:border-b dark:border-[#2A2C30] px-4 py-3.5 flex items-center justify-between transition-colors">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 bg-white/20 dark:bg-blue-600/20 dark:border dark:border-blue-500/30 backdrop-blur-sm rounded-lg flex items-center justify-center">
            <Sparkles size={14} className="text-white dark:text-blue-400" />
          </div>
          <div>
            <p className="text-white dark:text-[#F5F5F5] font-bold text-sm leading-none">AI Summary</p>
            <p className="text-white/70 dark:text-[#A1A1AA] text-[10px] mt-0.5">Powered by Google Gemini</p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-white/15 hover:bg-white/25 dark:bg-[#1D1F22] dark:hover:bg-[#2A2C30] text-white dark:text-[#F5F5F5] text-[11px] font-semibold transition-all duration-150 border border-white/20 dark:border-[#2A2C30]"
            title="Copy summary"
          >
            {copied ? (
              <><CheckCheck size={12} className="text-emerald-400" /><span>Copied!</span></>
            ) : (
              <><Copy size={12} /><span>Copy</span></>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-white/15 hover:bg-white/25 dark:bg-[#1D1F22] dark:hover:bg-[#2A2C30] text-white dark:text-[#F5F5F5] text-[11px] font-semibold transition-all duration-150 border border-white/20 dark:border-[#2A2C30]"
            title="Download summary as .txt"
          >
            <Download size={12} />
            <span className="hidden sm:inline">Download</span>
          </button>
        </div>
      </div>

      {/* Summary text */}
      <div className="bg-gradient-to-b from-blue-50/50 to-white dark:from-[#111214] dark:to-[#111214] p-4.5 sm:p-5 transition-colors">
        <p className="text-sm text-gray-800 dark:text-[#F5F5F5] leading-relaxed whitespace-pre-line font-normal">{summary}</p>
        <p className="text-[11px] text-gray-500 dark:text-[#71717A] mt-4 pt-3 border-t border-gray-100 dark:border-[#2A2C30] italic flex items-center gap-1.5">
          <span>⚕️</span>
          <span>This summary is for informational purposes only. Always consult a qualified healthcare professional for medical advice.</span>
        </p>
      </div>
    </div>
  );
};

export default AISummary;
