import React, { useState } from 'react';
import { Sparkles, Copy, Download, CheckCheck } from 'lucide-react';
import { showToast } from '../utils/toast';

/**
 * AISummary Component
 * Displays the patient-friendly AI-generated summary with copy and download actions.
 *
 * @param {string} summary - The patient-friendly summary text from Gemini
 * @param {string} reportTitle - Report title for download filename
 */
const AISummary = ({ summary, reportTitle = 'Medical Report' }) => {
  const [copied, setCopied] = useState(false);

  if (!summary) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      showToast.success('Summary copied to clipboard!');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = summary;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      showToast.success('Summary copied!');
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handleDownload = () => {
    const content = `MediTrack AI Summary\n${'='.repeat(40)}\nReport: ${reportTitle}\nGenerated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n\n${summary}\n\n${'─'.repeat(40)}\nGenerated by MediTrack using Gemini AI.\nThis summary is for informational purposes only. Always consult a qualified healthcare professional for medical advice.`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportTitle.replace(/\s+/g, '_')}_AI_Summary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast.success('Summary downloaded!');
  };

  return (
    <div className="rounded-2xl overflow-hidden border border-blue-200 shadow-sm">
      {/* Header gradient */}
      <div className="bg-gradient-to-r from-blue-600 to-violet-600 px-4 py-3.5 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 bg-white/20 backdrop-blur-sm rounded-lg flex items-center justify-center">
            <Sparkles size={14} className="text-white" />
          </div>
          <div>
            <p className="text-white font-bold text-sm leading-none">AI Summary</p>
            <p className="text-white/70 text-[10px] mt-0.5">Powered by Google Gemini</p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-white/15 hover:bg-white/25 text-white text-[11px] font-semibold transition-all duration-150 border border-white/20"
            title="Copy summary"
          >
            {copied ? (
              <><CheckCheck size={12} /><span>Copied!</span></>
            ) : (
              <><Copy size={12} /><span>Copy</span></>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-white/15 hover:bg-white/25 text-white text-[11px] font-semibold transition-all duration-150 border border-white/20"
            title="Download summary as .txt"
          >
            <Download size={12} />
            <span className="hidden sm:inline">Download</span>
          </button>
        </div>
      </div>

      {/* Summary text */}
      <div className="bg-gradient-to-b from-blue-50/50 to-white p-4">
        <p className="text-sm text-gray-700 leading-relaxed">{summary}</p>
        <p className="text-[10px] text-gray-400 mt-3 pt-3 border-t border-gray-100 italic">
          ⚕️ This summary is for informational purposes only. Always consult a qualified healthcare professional for medical advice.
        </p>
      </div>
    </div>
  );
};

export default AISummary;
